# Generated by Django 5.0.2 on 2024-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefonoCliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
    ]
