# Generated by Django 5.0.2 on 2024-05-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoservicio',
            old_name='autorPS',
            new_name='autorPSId',
        ),
    ]
