# Generated by Django 5.0.2 on 2024-05-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_autorps_productoservicio_autorpsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoservicio',
            old_name='costoPS',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='productoservicio',
            old_name='descripcionPS',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='productoservicio',
            old_name='estadoPS',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='productoservicio',
            old_name='nombrePS',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='productoservicio',
            old_name='precioUnitarioPS',
            new_name='precioUnitario',
        ),
    ]
