# Generated by Django 5.0.2 on 2024-05-10 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0003_alter_cliente_author'),
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('totalVenta', models.PositiveIntegerField()),
                ('observacionVenta', models.CharField(max_length=280, verbose_name='Observación de la venta')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idCliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
                'ordering': ['fechaVenta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto/Servicio')),
                ('cantidad', models.PositiveIntegerField()),
                ('idProducto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.productoservicio')),
                ('idVenta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'verbose_name': 'DetalleVenta',
                'verbose_name_plural': 'DetalleVentas',
                'db_table': 'DetalleVentas',
                'ordering': ['idVenta'],
            },
        ),
    ]
