# Generated by Django 5.0.2 on 2024-05-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
