# Generated by Django 5.0.2 on 2024-05-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_costops_productoservicio_costo_and_more'),
        ('venta', '0003_rename_author_venta_autorventa_venta_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productoId',
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioAcumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('idVenta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
                ('productoId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.productoservicio')),
            ],
        ),
    ]
