# Generated by Django 5.0.2 on 2024-05-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_remove_venta_cantidad_remove_venta_productoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='productoId',
            new_name='producto',
        ),
    ]
