# Generated by Django 5.0.2 on 2024-05-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_rename_productoid_detalleventa_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='totalVenta',
        ),
    ]
