# Generated by Django 5.0.2 on 2024-05-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_remove_venta_totalventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'detalleVenta', 'verbose_name_plural': 'detalleVentas'},
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalleVenta',
        ),
    ]
